### ISSUE TITLE
Cross-thread UI access error logged to VS output window

### ISSUE THREAD

**Issue by daiplusplus** [madskristensen/SvgViewer#7]
I'll preface this bug report with my own personal thank-you for making this extension - it's really helped me with switching from to SVG graphics when modernizing my web projects.

As for the bug report...

* Visual Studio 2019 Enterprise, 16.10
* SVG Viewer 10.0.13 (dated 2021-06-12)... I just realized that's _yesterday_.

Repro steps:

1. Have a .NET Core 3.1 class-library project (not an ASP.NET Core project) that contains `.svg` files.
1. Mouse-over them in the Solution Explorer
1. This appears in the Output > Extensions window:

```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at SvgViewer.SvgAdornment.<GenerateImageAsync>d__6.MoveNext() in C:\projects\svgviewer\src\Adornments\SvgAdornment.cs:line 77
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at SvgViewer.SvgAdornment.<GenerateImageAsync>d__6.MoveNext() in C:\projects\svgviewer\src\Adornments\SvgAdornment.cs:line 77<---
```

**Comment by madskristensen** [comment]
I can't reproduce the issue, but I moved a try/catch block such that line 77 is now handled in case of exceptions. This should take care of the  stack trace showing up in the output window

**Comment by madskristensen** [comment]
Fixed
